version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=your_aws_access_key_id  # Substitua pela sua chave de acesso AWS
      - AWS_SECRET_ACCESS_KEY=your_aws_secret_access_key  # Substitua pela sua chave secreta AWS
      - DYNAMODB_REGION=us-west-2
      - DYNAMODB_TABLE_NAME=YourDynamoDBTableName
      - ELASTICSEARCH_HOST=http://your-elasticsearch-host:9200  # Substitua pelo endereço do Elasticsearch existente
      - MYSQL_HOST=your-mysql-host  # Substitua pelo endereço do MySQL existente
      - MYSQL_DATABASE=my_database
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_TABLE_NAME=dados #your_mysql_table_name
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
